---
- include: install_odbc.yml
  when: iasterisk_odbc_support
- include: install.yml
  when: not skip_install is defined
- include: configure.yml
  when: configure_user is defined
- include: configure_odbc.yml
  when: iasterisk_odbc_support
