---
galaxy_info:
  author: Doug Smith
  description: Installs / Uninstalls Asterisk from source on Centos
  license: MIT
  min_ansible_version: 1.8
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your 
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: EL
    versions:
     - 6
  galaxy_tags:
    - networking
    - packaging
    - system

dependencies: []
  
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
